# Generated by Django 3.2.5 on 2021-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_track_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sent_email',
            field=models.BooleanField(default=False),
        ),
    ]
